    util.keep_running()

	kicks = menu.list(menu.my_root(), ":skull: Kicks", {"skull"}, "Edit The Players Status.", function(); end)

--------------------------------------------------------------------------------------------------------------------------
    _missversus_ = menu.list(kicks, "_missversus_", {"skull_missversus_"}, "Edit The Players Status.", function(); end)

        menu.action(_missversus_, "Check _missversus_", {"online_missversus_"}, "", function(on)
            menu.trigger_commands("historyadd" .. " _missversus_")
            menu.trigger_commands("findplayer" .. " _missversus_")
        end)

        menu.toggle_loop(_missversus_, "History Kick _missversus_", {""}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>_missversus_ [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    crustycrab99 = menu.list(kicks, "crustycrab99", {"skullcrustycrab99"}, "Edit The Players Status.", function(); end)

        menu.action(crustycrab99, "Check crustycrab99", {"onlinecrustycrab99"}, "", function(on)
            menu.trigger_commands("historyadd" .. " crustycrab99")
            menu.trigger_commands("findplayer" .. " crustycrab99")
        end)

        menu.toggle_loop(crustycrab99, "History Kick crustycrab99", {""}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>crustycrab99 [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    Bitflat = menu.list(kicks, "Bitflat", {"skullBitflat"}, "Edit The Players Status.", function(); end)
        
        menu.action(Bitflat, "Check Bitflat", {"onlineBitflat"}, "", function(on)
            menu.trigger_commands("historyadd" .. " Bitflat")
            menu.trigger_commands("findplayer" .. " Bitflat")
        end)

        menu.toggle_loop(Bitflat, "History Kick Bitflat", {""}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>Bitflat [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    GERBully1193 = menu.list(kicks, "GER-Bully1193", {"skullGER-Bully1193"}, "Edit The Players Status.", function(); end)

        menu.action(GERBully1193, "Check GER-Bully1193", {"onlineGER-Bully1193"}, "", function(on)
            menu.trigger_commands("historyadd" .. " GER-Bully1193")
            menu.trigger_commands("findplayer" .. " GER-Bully1193")
        end)

        menu.toggle_loop(GERBully1193, "History Kick GER-Bully1193", {""}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>GER-Bully1193 [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    Suse__ = menu.list(kicks, "Suse__", {"skullSuse__"}, "Edit The Players Status.", function(); end)

        menu.action(Suse__, "Check Suse__", {"onlineSuse__"}, "", function(on)
            menu.trigger_commands("historyadd" .. " Suse__")
            menu.trigger_commands("findplayer" .. " Suse__")
        end)

        menu.toggle_loop(Suse__, "History Kick Suse__", {"hkick3"}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>Suse__ [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    MrXGTA = menu.list(kicks, "Mr-X-GTA", {"skullMr-X-GTA"}, "Edit The Players Status.", function(); end)

        menu.action(MrXGTA, "Check Mr-X-GTA", {"onlineMr-X-GTA"}, "", function(on)
            menu.trigger_commands("historyadd" .. " Mr-X-GTA")
            menu.trigger_commands("findplayer" .. " Mr-X-GTA")
        end)

        menu.toggle_loop(MrXGTA, "History Kick Mr-X-GTA", {"hkick4"}, "", function(on_toggle)
            local BlindFire = menu.ref_by_path("Online>Player History>Mr-X-GTA [Public]>Blind-Fire Kick>Breakup")
            menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    Prizuhm = menu.list(kicks, "Prizuhm", {"skullPrizuhm"}, "Edit The Players Status.", function(); end)

        menu.action(Prizuhm, "Check Prizuhm", {"onlinePrizuhm"}, "", function(on)
            menu.trigger_commands("historyadd" .. " Prizuhm")
            menu.trigger_commands("findplayer" .. " Prizuhm")
        end)

        menu.toggle_loop(Prizuhm, "History Kick Prizuhm", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>Prizuhm [Public]>Blind-Fire Kick>Breakup")
        menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    VAGlNA = menu.list(kicks, "-V-A-G-l-N-A-", {"skull-V-A-G-l-N-A-"}, "Edit The Players Status.", function(); end)

        menu.action(VAGlNA, "Check -V-A-G-l-N-A-", {"online-V-A-G-l-N-A-"}, "", function(on)
            menu.trigger_commands("historyadd" .. " -V-A-G-l-N-A-")
            menu.trigger_commands("findplayer" .. " -V-A-G-l-N-A-")
        end)

        menu.toggle_loop(VAGlNA, "History Kick -V-A-G-l-N-A-", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>-V-A-G-l-N-A- [Public]>Blind-Fire Kick>Breakup")
        menu.trigger_command(BlindFire)
        end)
--------------------------------------------------------------------------------------------------------------------------
    NyHuya22 = menu.list(kicks, "NyHuya22", {"skullNyHuya22"}, "Edit The Players Status.", function(); end)

        menu.action(NyHuya22, "Check NyHuya22", {"onlineNyHuya22"}, "", function(on)
            menu.trigger_commands("historyadd" .. " NyHuya22")
            menu.trigger_commands("findplayer" .. " NyHuya22")
        end)

        menu.toggle_loop(NyHuya22, "History Kick NyHuya22", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>NyHuya22 [Public]>Blind-Fire Kick>Breakup")
        menu.trigger_command(BlindFire)
        end)
        

    crashes = menu.list(menu.my_root(), ":skull: Crashes", {"skulling"}, "Edit the Players Online Status To Story Mode To Send Pipebomb Even If It Says Story Mode.", function(); end)

        menu.toggle_loop(crashes, "If Only We Had Remote Crashes Still :(", {""}, "", function(on_toggle)
            --local BlindFire = menu.ref_by_path("Online>Player History>Bitflat [Public]>Send Pipebomb")
            --menu.trigger_command(BlindFire)
            util.toast("If Only We Had Remote Crashes Still :L")
            util.toast("If Only We Had Remote Crashes Still :l")
            util.toast("If Only We Had Remote Crashes Still :i")
            util.toast("If Only We Had Remote Crashes Still :c")
            util.toast("If Only We Had Remote Crashes Still :B")
            util.toast("If Only We Had Remote Crashes Still :T")
            util.toast("If Only We Had Remote Crashes Still :E")
            util.toast("If Only We Had Remote Crashes Still :z")
            util.toast("If Only We Had Remote Crashes Still :r")
            util.toast("If Only We Had Remote Crashes Still :(")
            util.log("If Only We Had Remote Crashes Still :'(")
        end)

--[[
        menu.toggle_loop(crashes, "History Crash Bitflat", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>Bitflat [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash GER-Bully1193", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>GER-Bully1193 [Story Mode]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash Suse__", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>Suse__ [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash Mr-X-GTA", {"hcrash4"}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>Mr-X-GTA [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash Prizuhm", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>Prizuhm [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash -V-A-G-l-N-A-", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>-V-A-G-l-N-A- [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)

        menu.toggle_loop(crashes, "History Crash NyHuya22", {""}, "", function(on_toggle)
        local BlindFire = menu.ref_by_path("Online>Player History>NyHuya22 [Public]>Send Pipebomb")
        menu.trigger_command(BlindFire)
        end)
]]
        ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    util.on_stop(function()
end)