
--[[
-- Fake Menu Hooks
util.log(SOCIALCLUB.SC_ACCOUNT_INFO_GET_NICKNAME() .. "'s social club loaded.")
util.log("Initialized Corrupt Stats")
--util.yield(1500)
util.log("Syncronizing Corrupt Globals")
--util.yield(1000)
util.log("Loading Hooks...")
--util.yield(1500)
util.log("Initialized MH")
--util.yield(500)
util.log("Getting IDP pointer")
--util.yield(100)
util.log("Getting GLT pointer")
--util.yield(100)
util.log("Getting GSHIN pointer")
--util.yield(100)
util.log("Getting GED pointer")
--util.yield(100)
util.log("Getting TSE pointer")
--util.yield(100)
util.log("Getting TFR pointer")
--util.yield(100)
util.log("Getting NRCOE pointer")
--util.yield(100)
util.log("Getting ISE pointer")
--util.yield(100)
util.log("Getting VRF pointer")
--util.yield(100)
util.log("Getting NRT pointer")
--util.yield(100)
util.log("Getting penis pointier")
--util.yield(100)
util.log("Getting WLD pointer")
--util.yield(100)
util.log("Getting GLB pointer")
--util.yield(100)
util.log("Initialized GN")
util.yield()
util.log("Hook GED")
util.yield()
util.log("Hook GSHIN")
util.yield()
util.log("Hook GLT")
util.yield()
util.log("Hook ISE")
util.yield()
util.log("Hook IDP")
--util.yield(500)
util.log("init_thread - exit code 0")
util.yield()
util.log("Loading Configuration")
util.yield()
util.log("Loading Custom Textures")
util.yield()
util.log("Loaded SPVSB")
util.yield()
util.log("Fetched DHC")
util.yield()
util.log("Loaded GXT strings")
util.yield()
util.log("Scanned 1.66-2845 for 206 sigs in 75.09238 ms (204 from cache)")
--util.yield(1000)
util.log("Doing minimal init.")
--util.yield(1000)
util.log("Game has finished loading. Did main hooks in 202.02545 ms.")
--util.yield(1500)
util.log("Corrupt Stats Injected Successfully")
--util.yield(150)
util.log(SOCIALCLUB.SC_ACCOUNT_INFO_GET_NICKNAME() .. "'s account bricked successfully!")
]]