_GT_veh_weap={}

_GT_veh_weap.list_prjctl={
gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_APC_CANNON"),
gameplay.get_hash_key("VEHICLE_WEAPON_APC_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_CHERNO_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_BARRAGE"),
gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON"),
gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY"),
gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_GL"),
gameplay.get_hash_key("VEHICLE_WEAPON_MONSTER3_GLKIN"),
gameplay.get_hash_key("VEHICLE_WEAPON_MORTAR_KINETIC"),
gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_TURRET_GL"),
gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_PLANE_ROCKET"),
gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_BARRAGE"),
gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_GL"),
gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_RCTANK_ROCKET"),
gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_ROCKET"),
gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_SPACE_ROCKET"),
gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_BARRAGE"),
gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_TORPEDO"),
gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MORTAR"),
gameplay.get_hash_key("VEHICLE_WEAPON_TANK"),
gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_TRAILER_MISSILE"),
gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MISSILE"),
}

_GT_veh_weap.list_mg={
--gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MINIGUN"),--"Akula MG",turret
gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_BUZZARD"),--"Buzzard MG",
3405172033,--"Annihilator MG", --Annihilator Stealth
gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER_50CAL"),--"Bruiser MG",
gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS_50CAL"),--"Brutus MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE_DUALMINIGUN"),--"Deathbike MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR4_50CAL"),--"Dominator MG",
gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER2_50CAL"),--"Impaler MG",
gameplay.get_hash_key("VEHICLE_WEAPON_IMPERATOR_50CAL"),--"Imperator MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ISSI4_50CAL"),--"Issi MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB_50CAL"),--"Scarab MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN4_50CAL"),--"Slamvan MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ZR380_50CAL"),--"ZR380 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ARDENT_MG"),--"Ardent MG",
gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_CANNON"),--"B-11 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_CANNON_BLAZER"),--"Blazer MG",
3940737434,--"Vehicle MG", --contract vehicles mg
gameplay.get_hash_key("VEHICLE_WEAPON_COMET_MG"),--"Comet MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MG"),--"Deluxo MG",
gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER2_50CAL_LASER"),--"Bruiser MG",
gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS2_50CAL_LASER"),--"Brutus MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE2_MINIGUN_LASER"),--"Deathbike MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR5_50CAL_LASER"),--"Dominator MG",
gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER3_50CAL_LASER"),--"Impaler MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ISSI5_50CAL_LASER"),--"Issi MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB2_50CAL_LASER"),--"Scarab MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN5_50CAL_LASER"),--"Slamvan MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ZR3802_50CAL_LASER"),--"ZR380 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_HAVOK_MINIGUN"),--"Helicopter MG",
gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_LAZER"),--"Plane MG",
gameplay.get_hash_key("VEHICLE_WEAPON_JB700_MG"),--"JB700 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MG"),--"Plane MG",
gameplay.get_hash_key("VEHICLE_WEAPON_MOGUL_DUALNOSE"),--"Mogul MG",
gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MG"),--"Mule MG",
gameplay.get_hash_key("VEHICLE_WEAPON_NIGHTSHARK_MG"),--"Nightshark MG",
gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MG"),--"Oppressor Mk1 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_CANNON"),--"Oppressor Mk2 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MG"),--"Oppressor Mk2 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_PARAGON2_MG"),--"Paragon MG",
gameplay.get_hash_key("VEHICLE_WEAPON_REVOLTER_MG"),--"Revolter MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_CANNON"),--"Rogue MG",
gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MG"),--"Rogue MG",
gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_BULLET"),--"Ruiner 2000 MG",
gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_SAVAGE"),--"Savage MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SAVESTRA_MG"),--"Savestra MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MG"),--"Scramjet MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SEABREEZE_MG"),--"Seabreeze MG",
2431961420,--"Sparrow MG", --Sparrow basic gun
gameplay.get_hash_key("VEHICLE_WEAPON_SPEEDO4_MG"),--"Speedovan MG",
gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MG"),--"Vehicle MG",
gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MG"),--"Thruster MG",
gameplay.get_hash_key("VEHICLE_WEAPON_TULA_NOSEMG"),--"Tula MG",
gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MG"),--"Vigilante MG",
gameplay.get_hash_key("VEHICLE_WEAPON_VISERIS_MG"),--"Viseris MG",
gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_FIXEDMINIGUN"),--"Weaponized Tampa MG",
gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MINI"),--"Pounder MG",
}

_GT_veh_weap.list_mg_dist={
--[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MINIGUN")]= 100,--"Akula MG", turret
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_BUZZARD")]= 180,-- 1186503822 "Buzzard MG",
[3405172033] = 180,--"Annihilator MG", --Annihilator Stealth
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER_50CAL")]= 100,--"Bruiser MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS_50CAL")]= 100,--"Brutus MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE_DUALMINIGUN")]= 100,--"Deathbike MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR4_50CAL")]= 100,--"Dominator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER2_50CAL")]= 100,--"Impaler MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPERATOR_50CAL")]= 100,--"Imperator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ISSI4_50CAL")]= 100,--"Issi MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB_50CAL")]= 100,--"Scarab MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN4_50CAL")]= 100,--"Slamvan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ZR380_50CAL")]= 100,--"ZR380 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ARDENT_MG")]= 100,--"Ardent MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_CANNON")]= 220,--"B-11 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_CANNON_BLAZER")]= 100,--"Blazer MG",
[3940737434] = 100,--"Vehicle MG", --contract vehicles mg
[gameplay.get_hash_key("VEHICLE_WEAPON_COMET_MG")]= 100,--"Comet MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MG")]= 100,--"Deluxo MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER2_50CAL_LASER")]= 100,--"Bruiser MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS2_50CAL_LASER")]= 100,--"Brutus MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE2_MINIGUN_LASER")]= 100,--"Deathbike MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR5_50CAL_LASER")]= 100,--"Dominator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER3_50CAL_LASER")]= 100,--"Impaler MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ISSI5_50CAL_LASER")]= 100,--"Issi MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB2_50CAL_LASER")]= 100,--"Scarab MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN5_50CAL_LASER")]= 100,--"Slamvan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ZR3802_50CAL_LASER")]= 100,--"ZR380 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_HAVOK_MINIGUN")]= 200,--"Helicopter MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_LAZER")]= 180,--"Plane MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_JB700_MG")]= 100,--"JB700 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MG")]= 250,--"Plane MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_MOGUL_DUALNOSE")]= 250,--"Mogul MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MG")]= 100,--"Mule MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_NIGHTSHARK_MG")]= 100,--"Nightshark MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MG")]= 100,--"Oppressor Mk1 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_CANNON")]= 150,--"Oppressor Mk2 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MG")]= 100,--"Oppressor Mk2 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PARAGON2_MG")]= 100,--"Paragon MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_REVOLTER_MG")]= 100,--"Revolter MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_CANNON")]= 200,--"Rogue MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MG")]= 250,--"Rogue MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_BULLET")]= 100,--"Ruiner 2000 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_SAVAGE")]= 130,--"Savage MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SAVESTRA_MG")]= 100,--"Savestra MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MG")]= 100,--"Scramjet MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SEABREEZE_MG")]= 250,--"Seabreeze MG",
[2431961420]=200,--"Sparrow MG", --Sparrow basic gun
[gameplay.get_hash_key("VEHICLE_WEAPON_SPEEDO4_MG")]= 100,--"Speedovan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MG")]= 100,--"Vehicle MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MG")]= 200,--"Thruster MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_TULA_NOSEMG")]= 250,--"Tula MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MG")]= 100,--"Vigilante MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_VISERIS_MG")]= 100,--"Viseris MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_FIXEDMINIGUN")]= 130,--"Weaponized Tampa MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MINI")]= 100,--"Pounder MG",
}

_GT_veh_weap.type={
[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_CANNON")]="Tank",
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_CHERNO_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_BARRAGE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON")]="Tank",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY")]="Tank",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_GL")]="Grenade",
[gameplay.get_hash_key("VEHICLE_WEAPON_MONSTER3_GLKIN")]="Grenade",
[gameplay.get_hash_key("VEHICLE_WEAPON_MORTAR_KINETIC")]="Mortar",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_TURRET_GL")]="Grenade",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLANE_ROCKET")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_BARRAGE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_GL")]="Grenade",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_RCTANK_ROCKET")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_ROCKET")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_SPACE_ROCKET")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_BARRAGE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_TORPEDO")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MORTAR")]="Mortar",
[gameplay.get_hash_key("VEHICLE_WEAPON_TANK")]="Tank",
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_TRAILER_MISSILE")]="Missile",
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MISSILE")]="Missile",
--[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MINIGUN")]="MG", turret
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_BUZZARD")]="MG",
[3405172033]="MG",--"Annihilator MG", --Annihilator Stealth
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER_50CAL")]="MG",--"Bruiser MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS_50CAL")]="MG",--"Brutus MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE_DUALMINIGUN")]="MG",--"Deathbike MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR4_50CAL")]="MG",--"Dominator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER2_50CAL")]="MG",--"Impaler MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPERATOR_50CAL")]="MG",--"Imperator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ISSI4_50CAL")]="MG",--"Issi MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB_50CAL")]="MG",--"Scarab MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN4_50CAL")]="MG",--"Slamvan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ZR380_50CAL")]="MG",--"ZR380 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ARDENT_MG")]="MG",--"Ardent MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_CANNON")]="MG",--"B-11 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_CANNON_BLAZER")]="MG",--"Blazer MG",
[3940737434]="MG",--"Vehicle MG", --contract vehicles mg
[gameplay.get_hash_key("VEHICLE_WEAPON_COMET_MG")]="MG",--"Comet MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MG")]="MG",--"Deluxo MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUISER2_50CAL_LASER")]="MG",--"Bruiser MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_BRUTUS2_50CAL_LASER")]="MG",--"Brutus MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DEATHBIKE2_MINIGUN_LASER")]="MG",--"Deathbike MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOMINATOR5_50CAL_LASER")]="MG",--"Dominator MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_IMPALER3_50CAL_LASER")]="MG",--"Impaler MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ISSI5_50CAL_LASER")]="MG",--"Issi MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCARAB2_50CAL_LASER")]="MG",--"Scarab MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SLAMVAN5_50CAL_LASER")]="MG",--"Slamvan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ZR3802_50CAL_LASER")]="MG",--"ZR380 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_HAVOK_MINIGUN")]="MG",--"Helicopter MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_LAZER")]="MG",--"Plane MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_JB700_MG")]="MG",--"JB700 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MG")]="MG",--"Plane MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_MOGUL_DUALNOSE")]="MG",--"Mogul MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MG")]="MG",--"Mule MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_NIGHTSHARK_MG")]="MG",--"Nightshark MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MG")]="MG",--"Oppressor Mk1 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_CANNON")]="MG",--"Oppressor Mk2 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MG")]="MG",--"Oppressor Mk2 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PARAGON2_MG")]="MG",--"Paragon MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_REVOLTER_MG")]="MG",--"Revolter MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_CANNON")]="MG",--"Rogue MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MG")]="MG",--"Rogue MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_BULLET")]="MG",--"Ruiner 2000 MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLAYER_SAVAGE")]="MG",--"Savage MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SAVESTRA_MG")]="MG",--"Savestra MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MG")]="MG",--"Scramjet MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SEABREEZE_MG")]="MG",--"Seabreeze MG",
[2431961420]="MG",--"Sparrow MG", --Sparrow basic gun
[gameplay.get_hash_key("VEHICLE_WEAPON_SPEEDO4_MG")]="MG",--"Speedovan MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MG")]="MG",--"Vehicle MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MG")]="MG",--"Thruster MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_TULA_NOSEMG")]="MG",--"Tula MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MG")]="MG",--"Vigilante MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_VISERIS_MG")]="MG",--"Viseris MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_FIXEDMINIGUN")]="MG",--"Weaponized Tampa MG",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MINI")]="MG",--"Pounder MG",
}

_GT_veh_weap.obj={
[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MISSILE")]=4083544953,
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_CANNON")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_MISSILE")]=245271664,
[gameplay.get_hash_key("VEHICLE_WEAPON_CHERNO_MISSILE")]=705446731,
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MISSILE")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_BARRAGE")]=918615565,
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_MISSILE")]=4083544953,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_GL")]=3141319142,
[gameplay.get_hash_key("VEHICLE_WEAPON_MONSTER3_GLKIN")]=3141319142,
[gameplay.get_hash_key("VEHICLE_WEAPON_MORTAR_KINETIC")]=2074250388,
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MISSILE")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_TURRET_GL")]=3141319142,
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_PLANE_ROCKET")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_BARRAGE")]=245271664,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_GL")]=3141319142,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MISSILE")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_RCTANK_ROCKET")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MISSILE")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_ROCKET")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_SPACE_ROCKET")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_BARRAGE")]=918615565,
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_MISSILE")]=1005810318,
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_TORPEDO")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MISSILE")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MORTAR")]=2074250388,
[gameplay.get_hash_key("VEHICLE_WEAPON_TANK")]=2586970039,
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MISSILE")]=4845511,
[gameplay.get_hash_key("VEHICLE_WEAPON_TRAILER_MISSILE")]=1582836606,
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MISSILE")]=4845511,
}


_GT_veh_weap.ofst={
[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_CANNON")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_CHERNO_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_BARRAGE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_GL")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_MONSTER3_GLKIN")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_MORTAR_KINETIC")]=-1,
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_TURRET_GL")]=-2,
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_PLANE_ROCKET")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_BARRAGE")]=-2,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_GL")]=-2,
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_RCTANK_ROCKET")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MISSILE")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_ROCKET")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_SPACE_ROCKET")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_BARRAGE")]=3,
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_MISSILE")]=3,
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_TORPEDO")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MORTAR")]=-1,
[gameplay.get_hash_key("VEHICLE_WEAPON_TANK")]=2,
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_TRAILER_MISSILE")]=1,
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MISSILE")]=2,
}

_GT_veh_weap.dir={
[gameplay.get_hash_key("VEHICLE_WEAPON_AKULA_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_CANNON")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_APC_MISSILE")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_CHERNO_MISSILE")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_DELUXO_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_DOGFIGHTER_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_BARRAGE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_HUNTER_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_CANNON_HEAVY")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_KHANJALI_GL")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_MONSTER3_GLKIN")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_MORTAR_KINETIC")]="Rear",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_MULE4_TURRET_GL")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_OPPRESSOR2_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_PLANE_ROCKET")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_BARRAGE")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_GL")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_POUNDER2_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_RCTANK_ROCKET")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_ROGUE_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_RUINER_ROCKET")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_SCRAMJET_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_SPACE_ROCKET")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_BARRAGE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_STRIKEFORCE_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_SUBCAR_TORPEDO")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_TAMPA_MORTAR")]="Rear",
[gameplay.get_hash_key("VEHICLE_WEAPON_TANK")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_THRUSTER_MISSILE")]="Front",
[gameplay.get_hash_key("VEHICLE_WEAPON_TRAILER_MISSILE")]="Turret",
[gameplay.get_hash_key("VEHICLE_WEAPON_VIGILANTE_MISSILE")]="Front",
}

_GT_veh_weap.mg_pitch_ofst ={
[gameplay.get_hash_key("oppressor")]=1,
[gameplay.get_hash_key("oppressor2")]=-0.5,
[gameplay.get_hash_key("champion")]=0.25,
[gameplay.get_hash_key("seasparrow")]=1,
[gameplay.get_hash_key("seasparrow2")]=1,
[gameplay.get_hash_key("imperator")]=-0.5,
[gameplay.get_hash_key("imperator2")]=-0.5,
[gameplay.get_hash_key("imperator3")]=-0.5,
[gameplay.get_hash_key("bruiser")]=-0.5,
[gameplay.get_hash_key("bruiser2")]=-0.5,
[gameplay.get_hash_key("bruiser3")]=-0.5,
[gameplay.get_hash_key("deathbike")]=1,
[gameplay.get_hash_key("deathbike2")]=1,
[gameplay.get_hash_key("deathbike3")]=1,
[gameplay.get_hash_key("nightshark")]=-0.25,
[gameplay.get_hash_key("toreador")]=-0.5,
[gameplay.get_hash_key("patriot3")]=-0.5,
}

_GT_handheld_weap={}
_GT_handheld_weap.obj={
[gameplay.get_hash_key("weapon_rpg")] = 2586970039,
[gameplay.get_hash_key("weapon_stinger")] = 2586970039,
[gameplay.get_hash_key("weapon_compactlauncher")] = 1948242884,
[gameplay.get_hash_key("weapon_grenadelauncher")] = 1948242884,
[gameplay.get_hash_key("weapon_hominglauncher")] = 3148706974,
[gameplay.get_hash_key("weapon_firework")] = 439782367,
[gameplay.get_hash_key("weapon_emplauncher")] = 2450168807,
[gameplay.get_hash_key("weapon_flaregun")] = 665801196,
[gameplay.get_hash_key("weapon_grenade")] = 290600267,
[gameplay.get_hash_key("weapon_bzgas")] = 1591549914,
[gameplay.get_hash_key("weapon_molotov")] = 3414357965,
[gameplay.get_hash_key("weapon_stickybomb")] = 3184763647,
[gameplay.get_hash_key("weapon_proxmine")] = 1876445962, 
[gameplay.get_hash_key("weapon_snowball")] = 1297482736,
[gameplay.get_hash_key("weapon_pipebomb")] = 4121513285,
[gameplay.get_hash_key("weapon_ball")] = 3911017173,
[gameplay.get_hash_key("weapon_smokegrenade")] = 1948242884,--1591549914
[gameplay.get_hash_key("weapon_flare")] = 2730774144,
[gameplay.get_hash_key("weapon_raypistol")]=665801196,
}

_GT_handheld_weap.type={
[gameplay.get_hash_key("weapon_rpg")] = "Hand",
[gameplay.get_hash_key("weapon_stinger")] = "Hand",
[gameplay.get_hash_key("weapon_compactlauncher")] = "Hand",
[gameplay.get_hash_key("weapon_grenadelauncher")] = "Hand",
[gameplay.get_hash_key("weapon_hominglauncher")] = "Hand",
[gameplay.get_hash_key("weapon_firework")] = "Hand",
[gameplay.get_hash_key("weapon_emplauncher")] = "Hand",
[gameplay.get_hash_key("weapon_flaregun")] = "Hand",
[gameplay.get_hash_key("weapon_grenade")] = "Throw",
[gameplay.get_hash_key("weapon_bzgas")] = "Throw",
[gameplay.get_hash_key("weapon_molotov")] = "Throw",
[gameplay.get_hash_key("weapon_stickybomb")] = "Throw",
[gameplay.get_hash_key("weapon_proxmine")] = "Throw", 
[gameplay.get_hash_key("weapon_snowball")] = "Throw",
[gameplay.get_hash_key("weapon_pipebomb")] = "Throw",
[gameplay.get_hash_key("weapon_ball")] = "Throw",
[gameplay.get_hash_key("weapon_smokegrenade")] = "Throw",
[gameplay.get_hash_key("weapon_flare")] = "Throw",
[gameplay.get_hash_key("weapon_raypistol")]="Hand",
}


_G_GE_weap_range = {
[gameplay.get_hash_key("weapon_heavysniper_mk2")] = {
	[0]={
		[1]=1400,
		[2]=1400,
		[3]=1400,
		[4]=1400,
		[5]=1400,
		[6]=1400,
		[7]=1400,
		[8]=1400,
		[9]=1400,
		[10]=1400,
	},
	[1]={
		[1]=1400,
		[2]=1400,
		[3]=1400,
		[4]=1400,
		[5]=1400,
		[6]=1400,
		[7]=1400,
		[8]=1400,
		[9]=1400,
		[10]=1400,
	},
	[2]={
		[1]=1400,
		[2]=1400,
		[3]=1400,
		[4]=1400,
		[5]=1400,
		[6]=1400,
		[7]=1400,
		[8]=1400,
		[9]=1400,
		[10]=1400,
	},
},
[gameplay.get_hash_key("weapon_railgun")] = {
	[0]={
		[1]=500,
		[2]=500,
		[3]=500,
		[4]=500,
		[5]=500,
		[6]=500,
		[7]=500,
		[8]=500,
		[9]=500,
		[10]=500,
	},
	[1]={
		[1]=500,
		[2]=500,
		[3]=500,
		[4]=500,
		[5]=500,
		[6]=500,
		[7]=500,
		[8]=500,
		[9]=500,
		[10]=500,
	},
	[2]={
		[1]=500,
		[2]=500,
		[3]=500,
		[4]=500,
		[5]=500,
		[6]=500,
		[7]=500,
		[8]=500,
		[9]=500,
		[10]=500,
	},
},
[gameplay.get_hash_key("weapon_rpg")] = {
	[0]={
		[1]=490,
		[2]=477,
		[3]=500,
		[4]=506,
		[5]=512,
		[6]=517,
		[7]=520,
		[8]=524,
		[9]=530,
		[10]=536,
	},
	[1]={
		[1]=350,
		[2]=477,
		[3]=590,
		[4]=707,
		[5]=1050,
		[6]=1215,
		[7]=1369,
		[8]=1434,
		[9]=1500,
		[10]=1507,
	},
	[2]={
		[1]=300,
		[2]=300,
		[3]=300,
		[4]=300,
		[5]=300,
		[6]=300,
		[7]=300,
		[8]=300,
		[9]=300,
		[10]=300,
	},
},
[gameplay.get_hash_key("weapon_bzgas")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,	
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_stickybomb")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_proxmine")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_molotov")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_pipebomb")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_emplauncher")] = {
	[0]={
		[1]=33,
		[2]=48,
		[3]=60,
		[4]=80,
		[5]=97,
		[6]=110,
		[7]=135,
		[8]=155,
		[9]=180,
		[10]=200,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=30,
		[2]=30,
		[3]=30,
		[4]=30,
		[5]=30,
		[6]=30,
		[7]=30,
		[8]=30,
		[9]=30,
		[10]=30,
	},
},
[gameplay.get_hash_key("weapon_firework")] = {
	[0]={
		[1]=194,
		[2]=202,
		[3]=209,
		[4]=215,
		[5]=221,
		[6]=224,
		[7]=228,
		[8]=231,
		[9]=234,
		[10]=237,
	},
	[1]={
		[1]=175,
		[2]=195,
		[3]=284,
		[4]=369,
		[5]=454,
		[6]=536,
		[7]=614,
		[8]=693,
		[9]=765,
		[10]=839,
	},
	[2]={
		[1]=135,
		[2]=135,
		[3]=135,
		[4]=135,
		[5]=135,
		[6]=135,
		[7]=135,
		[8]=135,
		[9]=135,
		[10]=135,
	},
},
[gameplay.get_hash_key("weapon_grenadelauncher")] = {
	[0]={
		[1]=22,
		[2]=33,
		[3]=48,
		[4]=60,
		[5]=80,
		[6]=97,
		[7]=110,
		[8]=135,
		[9]=155,
		[10]=180,
	},
	[1]={
		[1]=320,
		[2]=930,
		[3]=1369,
		[4]=2500,
		[5]=3240,
		[6]=3600,
		[7]=3600,
		[8]=3600,
		[9]=3600,
		[10]=3600,
	},
	[2]={
		[1]=50,
		[2]=50,
		[3]=50,
		[4]=50,
		[5]=50,
		[6]=50,
		[7]=50,
		[8]=50,
		[9]=50,
		[10]=50,
	},
},
[gameplay.get_hash_key("weapon_raypistol")] = {
	[0]={
		[1]=137,
		[2]=275,
		[3]=411,
		[4]=547,
		[5]=685,
		[6]=821,
		[7]=956,
		[8]=1095,
		[9]=1231,
		[10]=1367,
	},
	[1]={
		[1]=137,
		[2]=275,
		[3]=411,
		[4]=547,
		[5]=685,
		[6]=821,
		[7]=956,
		[8]=1095,
		[9]=1231,
		[10]=1367,
	},
	[2]={
		[1]=100,
		[2]=100,
		[3]=100,
		[4]=100,
		[5]=100,
		[6]=100,
		[7]=100,
		[8]=100,
		[9]=100,
		[10]=100,
	},
},

}

--atomizer 100m
--rail gun 500m
--sniper rifle 1400
--homing launcher 1075m
--rpg stinger 1200m
--rpg 300m
--firework 135m
