KER_LANG_TABLE = {
    "Lobby Features",
    "Explosion Features",
    "Everyone Explode-Suicides",
    "Toxic Features",
    "Black Plague Crash All",
    "This will crash everyone with the plague. Did you mean to click this?",
    "Removes",
    "Freemode Death All",
    "AIO Kick All",
    "Slower, but better AIO",
    "Other Features / Tools",
    "Remove Vehicle Godmode for All",
    "Teleport everyone's vehicles to ocean",
    "Teleport everyone's vehicles to Maze Bank",
    "Vehicle Teleporting Load Iterations",
    "Check entire lobby for godmode",
    "Weapon Features",
    "Sticky Bomb Gun",
    "Improved Sticky Bomb Gun",
    "Explode All Stickybombs",
    "Clear Stickybombs",
    "Extinction Gun",
    "Better Extinction Gun",
    "Extinct",
    "Clear Extinct List",
    "Proximity Mine Gun",
    "Proximity Mine Gun",
    "Enable/Disable Proximity Mines",
    "Clear Proximity Mines",
    "Kill Aura",
    "KillAura",
    "KillAura Settings",
    "KillAura Settings",
    "Killaura Radius",
    "Blame Killaura on Me?",
    "Target Players?",
    "Target ONLY Players?",
    "Delete Vehicles of Peds?",
    "Delete peds after shooting?",
    "Draw Radius of Killaura?",
    "Draw peds in radius",
    "Spawn test peds",
    "Populate the map",
    "PvP / PvE Helper",
    "PvP / PvE Helper",
    "Silent Aimbot",
    "Silent Aimbot",
    "Silent Aim Settings",
    "Silent Aimbot Damage",
    "Silent Aimbot Range",
    "Silent Aimbot FOV",
    "Vehicle Mode",
    "Legit Silent Aim",
    "Vehicle-Head Check",
    "Target ONLY NPCs",
    "Hitbox: Head",
    "Hitbox: Body",
    "Hitbox: Pelvis",
    "Hitbox: Toe",
    "Hitbox: Hand",
    "Vehicle Aimbot",
    "Helicopter Aimbot",
    "Modify Missile Speed",
    "Set Missile Speed",
    "RPG Aimbot",
    "RPG Aimbot / Most Vehicles",
    "RPG Aimbot Settings",
    "Enable Javelin Mode",
    "RPG Aimbot Radius",
    "RPG Speed Multiplier",
    "RPG LOS Remove",
    "RPG Dashcam™",
    "Orbital Waypoint",
    "Orbital Strike Waypoint",
    "Sneaky Explosion",
    "Auto Car-Suicide",
    "Auto Car-Suicide",
    "Car Suicide Sneaky",
    "Legit Rapid Fire",
    "Legit Rapid Fire (fast-switch)",
    "Legit Rapid Fire Delay (ms)",
    "Tools",
    "Smooth TP",
    "Smooth Teleport",
    "Smooth Teleport Frames (v2)",
    "Reset Camera",
    "SmoothTP Settings",
    "Speed Modifier (x) /10",
    "Height of cam transition (meters)",
    "Draw Position",
    "Draw Entity Pool",
    "vehicles: ",
    "peds: ",
    "objects: ",
    "pickups: ",
    "Entity Pool Settings",
    "Draw Vehicles",
    "Vehicle Text Placement X",
    "Vehicle Text Placement Y",
    "Draw Peds",
    "Ped Text Placement X",
    "Ped Text Placement Y",
    "Draw Objects",
    "Object Text Placement X",
    "Object Text Placement Y",
    "Draw Pickups",
    "Pickups Text Placement X",
    "Pickups Text Placement Y",
    "Settings",
    "Text Size (/10)",
    "Others",
    "Yoink Control of All __",
    "Yoink Control Settings",
    "Range For Yoink",
    "Peds",
    "Vehicles",
    "Objects",
    "Pickups",
    "Vehicle Options",
    "Vehicle Tools",
    "Display Vehicle Rotation and Speed",
    "Set Vehicle Always Upside-Down",
    "Vehicle fast custom-turn",
    "Vehicle fast custom-turn scale (/10)",
    "Unlock Vehicle",
    "Unlock Vehicle that you Shoot",
    "Unlock Vehicle that you try to get into",
    "Turn Car On Instantly",
    "Auto-Features",
    "Auto-'perf' on getting in a vehicle",
    "Auto-'tune' on getting in a vehicle",
    "Velocity Multiplier",
    "Velocity Multiplier (BIND TO HOLD)",
    "Velocity Multiplier (Bound to LShift)",
    "Velocity Multiplier Multiplier (/100)",
    "Spawn Features",
    "Peds",
    "Cleanup all spawned peds",
    "Spawns",
    "Objects",
    "Cleanup all spawned objects",
    "Spawns",
    "Spawn frozen?",
    "Spawn godmode?",
    "Genrate Spawn Features",
    "----------Settings----------",
    "Invisible Explosion?",
    "Audible Explosion?",
    "Enable/Disable notifications",
    "Suicides",
    "Weapons",
    "Tools",
    "Trolling",
    "Make Player Explode Themselves",
    "Loop Explode Suicide",
    "Make Player Molotov Themselves",
    "Loop Molotov Suicide",
    "Change Explosion Delay (ms)",
    "Explosion Gun",
    "Vehicle Trolling",
    "Vehicle Trolling",
    "Place wall in front of player",
    "Drop Vehicle",
    "Drop vehicle on player",
    "Input Vehicle Name",
    "Make Vehicle Inivisble?",
    "Teleport Player's Vehicle",
    "Teleport Player Into Ocean",
    "Teleport Player Onto Maze Bank",
    "FakeLag Player's Vehicle",
    "Toss Features",
    "Toss Features",
    "Toss Player Around",
    "Get Weapon Impact",
    "Weapon Impact Debug",
    "Clear Location Memory",
    "Better Toss",
    "Toxic Features",
    "Toxic Features",
    "Invalid Warehouse Invite",
    "Removes",
    "Freemode Death",
    "AIO Kick",
    "Plague Crash",
    "Move Check",
    "Move Check",
    "Move Check Interval (ms)",
    "Pan",
    "Pan",
    "Number of fried fish",
    "Remove Pan",
    "Godmode Tools",
    "God Check",
    "Remove Player Godmode",
    "Remove Player Vehicle Godmode",
    "Smooth-Teleport",
    "Smooth Teleport",
    "Settings",
    "Blacklist from Silent Aimbot",
    "Blacklist from Auto Car-Suicide"
}