-- REPO/release train_control.lua
-- AUTOGENERATED CODE ON Sunday 2nd, July 2023 AT 09:25:38 PM
local SCRIPT_SOURCE = "REPO"
local SCRIPT_BRANCH = "release"
local BRANCH_LAST_COMMIT = "e3fa9f7e702205479816675e312e66b77e7d1ebe"
local SCRIPT_BRANCH_IDS = {"actions-fix","jackzscript","master","release"}
local SCRIPT_BRANCH_NAMES = {{"actions-fix"},{"jackzscript"},{"dev"},{"release"}}
-- END AUTOGENERATED CODE --

-- Train Control
-- Created By Jackz
local SCRIPT = "train_control"
VERSION = "1.1.9"


-- TEMPLATE: release/log.lua --
Log = {}
if SCRIPT_DEBUG == nil then
    SCRIPT_DEBUG = false
end
function Log._log(prefix, ...)
    local mod = debug.getinfo(3, "n").name or debug.getinfo(4, "n").name or "_anon_func"
    local msg = ""
    for _, a in ipairs(...) do
        if a == nil then a = "<nil>" end
        if type(a) == "table" then a = dumpTable(a) end
        msg = msg .. tostring(a) .. "\t"
    end
    if prefix then prefix = "[" .. prefix .. "] "
    else prefix = "" end
    util.log(string.format("%s%s:%s/%s: %s", prefix, SCRIPT_NAME, SCRIPT_SOURCE or "DEV", mod, msg))
end
function Log.debug(...)
    if SCRIPT_DEBUG then
        local arg = {...}
        Log._log("debug", arg)
    end
end
function Log.debugTable(table)
    if SCRIPT_DEBUG then
        local mod = debug.getinfo(3, "n").name or debug.getinfo(4, "n").name or "_anon_func"
        util.log(string.format("%s:%s/%s: %s", SCRIPT_NAME, SCRIPT_SOURCE or "DEV", mod, dumpTable(table)))
    end
end
function Log.warn(...)
    local arg = {...}
    Log._log("Warn", arg)
end
function Log.error(...)
    local arg = {...}
    Log._log("Error", arg)
end
function Log.severe(...)
    local arg = {...}
    Log._log("Severe", arg)
    util.stop_script()
end
function Log.log(...)
    local arg = {...}
    Log._log(nil, arg)
end

function dumpTable(o)
    if type(o) == 'table' then
       local s = '{ '
       for k,v in pairs(o) do
          if type(k) ~= 'number' then k = '"'..k..'"' end
          s = s .. '['..k..'] = ' .. dumpTable(v) .. ','
       end
       return s .. '} '
    elseif type(o) == "string" then
        return '"' .. o .. "'"
    else
       return tostring(o)
    end
end
-- END TEMPLATE --
-- TEMPLATE: release/repo.lua --
function download_resources_update(filepath, destOverwritePath)
    local lockPath = filesystem.scripts_dir() .. "/lib/" .. filepath .. ".lock"
    if filesystem.exists(lockPath) then
        util.log(SCRIPT_NAME .. ": Skipping resource update \" .. lib .. \", found update lockfile")
    end
    local lock = io.open(lockPath, "w")
    if lock == nil then
        util.toast(SCRIPT_NAME .. ": Could not create lockfile, skipping update", TOAST_ALL)
        return
    end
    lock:close()
    async_http.init("jackz.me", "/stand/get-lua.php?script=resources/" .. filepath .. "&source=" .. SCRIPT_SOURCE .. "&branch=" .. (SCRIPT_BRANCH or "master"), function(result, res_headers, status_code)
        os.remove(lockPath)
        if status_code ~= 200 or result:startswith("<") then
            util.toast("Resource returned invalid response for \"" .. filepath .. "\"\nSee logs for details")
            util.log(string.format("%s: Resource \"%s\" returned: %s", SCRIPT_NAME, filepath, result))
            return
        end
        local file = io.open(filesystem.resources_dir() .. (destOverwritePath or filepath), "w")
        if file == nil then
            util.toast("Could not write resource file for: " .. filepath .. "\nSee logs for details")
            util.log(string.format("%s: Resource \"%s\" file could not be created.", SCRIPT_NAME, filepath))
            return
        end
        Log.log("Updated resource ", filepath, "for", SCRIPT_NAME, "to branch", SCRIPT_BRANCH or "master")
        file:write(result:gsub("\r", "") .. "\n")
        file:close()
        util.toast(SCRIPT .. ": Automatically updated resource '" .. filepath .. "'")
    end, function(e)
        os.remove(lockPath)
        util.toast(SCRIPT .. " cannot load: Library files are missing. (" .. filepath .. ")", 10)
        util.stop_script()
    end)
    async_http.dispatch()
end

-- END TEMPLATE --
-- TEMPLATE: release/common.lua --
-- People keep trying to run stuff on non-stand
if not filesystem.stand_dir then
    print("Unsupported. Only stand is supported")
    return
end
----------------------------------------------------------------
-- Version Check
function get_version_info(version)
    if not version then error("Missing version", 2) end
    local major, minor, patch = version:match("(%d+)%.(%d+)%.(%d+)")
    return {
        major = tonumber(major) or 0,
        minor = tonumber(minor) or 0,
        patch = tonumber(patch) or 0
    }
end
function compare_version(a, b)
    local av = get_version_info(a)
    local bv = get_version_info(b)
    if not av or not bv then error("Missing versions to compare") end
    if av.major > bv.major then return 1
    elseif av.major < bv.major then return -1
    elseif av.minor > bv.minor then return 1
    elseif av.minor < bv.minor then return -1
    elseif av.patch > bv.patch then return 1
    elseif av.patch < bv.patch then return -1
    else return 0 end
end
if SCRIPT_BRANCH and SCRIPT_BRANCH == "release" then
    local VERSION_FILE_PATH = filesystem.store_dir() .. "jackz_versions.txt"
    if not filesystem.exists(VERSION_FILE_PATH) then
        local versionFile = io.open(VERSION_FILE_PATH, "w")
        if versionFile then
            versionFile:close()
        end
    end
    local versionFile = io.open(VERSION_FILE_PATH, "r+")
    if versionFile then
        local versions = {}
        for line in versionFile:lines("l") do
            local script, version = line:match("(%g+): (%g+)")
            if script then
                versions[script] = version
            end
        end
        if versions[SCRIPT_NAME] == nil or compare_version(VERSION, versions[SCRIPT_NAME]) == 1 then
            if versions[SCRIPT_NAME] ~= nil then
                async_http.init("jackz.me", "/stand/changelog.php?raw=1&script=" .. SCRIPT_NAME .. "&since=" .. versions[SCRIPT_NAME] .. "&branch=" .. (SCRIPT_BRANCH or "master"), function(result)
                    util.toast("Changelog for " .. SCRIPT_NAME .. " version " .. VERSION .. ":\n" .. result)
                end, function() util.log(SCRIPT_NAME ..": Could not get changelog") end)
                async_http.dispatch()
            end
            versions[SCRIPT_NAME] = VERSION
            versionFile:seek("set", 0)
            versionFile:write("# DO NOT EDIT ! File is used for changelogs\n")
            for script, version in pairs(versions) do
                versionFile:write(script .. ": " .. version .. "\n")
            end
        end
        versionFile:close()
    else
        util.log(SCRIPT_NAME .. ": Failed to access to version file")
    end
end

-- END Version Check
------------------------------------------------------------------
function show_busyspinner(text)
    HUD.BEGIN_TEXT_COMMAND_BUSYSPINNER_ON("STRING")
    HUD.ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME(text)
    HUD.END_TEXT_COMMAND_BUSYSPINNER_ON(2)
end

----------------------------------------------------------------
---- SCRIPT META - LIST
----------------------------------------------------------------
SCRIPT_META_LIST = menu.list(menu.my_root(), "Script Meta")
menu.divider(SCRIPT_META_LIST, SCRIPT_NAME .. " V" .. VERSION)
menu.hyperlink(SCRIPT_META_LIST, "Jackz's Guilded", "https://www.guilded.gg/i/k8bMDR7E?cid=918b2f61-989c-41c4-ba35-8fd0e289c35d&intent=chat", "Get help, submit suggestions, report bugs, or be with other users of my scripts")
menu.hyperlink(SCRIPT_META_LIST, "Jackz's Discord", "https://discord.gg/NnJrkGppfb", "Get help, submit suggestions, report bugs, or be with other users of my scripts")
menu.hyperlink(SCRIPT_META_LIST, "Github Source", "https://github.com/Jackzmc/lua-scripts", "View all my lua scripts on github")

----------------------------------------------------------------
---- VERSION
----------------------------------------------------------------
SCRIPT_BACKUP_PATH = filesystem.store_dir() .. "/old-" .. SCRIPT_FILENAME
SCRIPT_UPDATE_NEW_VERSION = "-error-"
menu.divider(SCRIPT_META_LIST, "Version")
--#P:MANUAL_ONLY
SCRIPT_META_UPDATE_ACTION = menu.action(SCRIPT_META_LIST, "Update", {}, "[invalid state]", function()
    util.toast("Updating")
    SCRIPT_META_UPDATE_ACTION:delete()
    SCRIPT_META_REVERT_ACTION:delete()
    download_script_update(SCRIPT_BRANCH, function()
        util.toast(SCRIPT .. " was updated to V" .. SCRIPT_UPDATE_NEW_VERSION .. "\nScript is restarting to apply changes", TOAST_ALL)
        util.restart_script()
    end, function()
        util.toast(SCRIPT .. ": Failed to update to V" .. SCRIPT_UPDATE_NEW_VERSION .. ".\nPlease download latest update manually.\nhttps://jackz.me/stand/get-latest-zip", 2)
    end)
end)
SCRIPT_META_REVERT_ACTION = menu.action(SCRIPT_META_LIST, "Revert", {}, "[invalid state]", function()
    SCRIPT_META_UPDATE_ACTION:delete()
    SCRIPT_META_REVERT_ACTION:delete()
    if filesystem.exists(SCRIPT_BACKUP_PATH) then
        os.rename(SCRIPT_BACKUP_PATH, filesystem.scripts_dir()  .. SCRIPT_RELPATH)
        os.remove(SCRIPT_BACKUP_PATH .. ".meta")
        util.toast(SCRIPT .. " was reverted to previous version\nScript is restarting to apply changes", TOAST_ALL)
        util.restart_script()
    else
        util.toast("There is no old verison to restore to")
    end
end)
SCRIPT_META_UPDATE_ACTION.visible = false
SCRIPT_META_REVERT_ACTION.visible = false
--#p:END
menu.hyperlink(SCRIPT_META_LIST, "View Changelog", "https://jackz.me/stand/changelog?html=1&reverse=1&script=" .. SCRIPT_NAME)
if SCRIPT_SOURCE == "MANUAL" then
    local branchIndex = 1
    for i, branch in ipairs(SCRIPT_BRANCH_IDS) do
        if branch == SCRIPT_BRANCH then
            branchIndex = i
        end
    end
    menu.list_select(SCRIPT_META_LIST, "Release Channel", {SCRIPT_NAME.."channel"}, "Sets the release channel for updates for this script.\nChanging the channel from release may result in bugs.", SCRIPT_BRANCH_NAMES, branchIndex, function(index, name)
        if SCRIPT_BRANCH_IDS[index] == nil then
            util.toast("Error: Invalid channel")
            return
        end
        show_busyspinner("Switching to " .. SCRIPT_BRANCH_IDS[index])
        download_script_update(SCRIPT_BRANCH_IDS[index], function()
            HUD.BUSYSPINNER_OFF()
            util.log(SCRIPT_NAME .. ": Released channel changed to " .. SCRIPT_BRANCH_IDS[index])
            util.toast("Release channel changed to " .. name .. " (" .. SCRIPT_BRANCH_IDS[index] .. ")")
            util.restart_script()
        end, function()
            util.toast("Failed to download latest version for release channel.")
        end)
    end)
else
    menu.readonly(SCRIPT_META_LIST, "Release Channel", "Use the manual version from https://jackz.me/stand/get-latest-zip to change the release channel.")
end
menu.readonly(SCRIPT_META_LIST, "Build Commit", BRANCH_LAST_COMMIT and BRANCH_LAST_COMMIT:sub(1,10) or "Dev Build")

----------------------------------------------------------------
---- MISC
----------------------------------------------------------------
menu.divider(SCRIPT_META_LIST, "")
if _lang ~= nil then
    menu.hyperlink(SCRIPT_META_LIST, "Help Translate", "https://jackz.me/stand/translate/?script=" .. SCRIPT, "If you wish to help translate, this script has default translations fed via google translate, but you can edit them here:\nOnce you make changes, top right includes a save button to get a -CHANGES.json file, send that my way.")
    _lang.add_language_selector_to_menu(SCRIPT_META_LIST)
    menu.action(SCRIPT_META_LIST, "Update Translation File", {}, "This will download the latest translation file for your currently selected language", function()
        show_busyspinner("Fetching translation file...")
        _lang.update_translation_file(SCRIPT)
        HUD.BUSYSPINNER_OFF()
    end)
end
menu.action(SCRIPT_META_LIST, "Upload Logs", {}, "Uploads the last ~20 lines of your stand log (%appdata%\\Stand\\Log.txt) to paste.jackz.me.\nLog uploads are unlisted and will expire 7 days after uploaded.\n\nUploaded log can be accessed from \"Open Uploaded Log\" button below once pressed", function()
    local logs = io.open(filesystem.stand_dir() .. "Log.txt", "r")
    if logs then
        show_busyspinner("Uploading logs....")
        async_http.init("paste.jackz.me", "/paste?textOnly=1&expires=604800", function(body)
            HUD.BUSYSPINNER_OFF()
            local lines = {}
            for s in body:gmatch("[^\r\n]+") do
                table.insert(lines, s)
            end
            local url = lines[3] or ("https://paste.jackz.me/" .. lines[1])
            util.copy_to_clipboard(url, true)
            util.toast("Uploaded: " .. url .. "\nCopied to clipboard", 2)
            menu.hyperlink(SCRIPT_META_LIST, "Open Uploaded Log", url)
                :setTemporary()
        end, function()
            util.toast("Failed to submit logs, network error")
            HUD.BUSYSPINNER_OFF()
        end)
        logs:seek("end", -3072)
        local content = logs:read("*a")
        local standVersion = menu.get_version().full
        async_http.set_post("text/plain",
            string.format("Script: %s\nSource: %s\nBranch: %s\nVersion: %s\nStand Version: %s\nCommit: %s\nLanguage: %s\n\n%s", SCRIPT_NAME, SCRIPT_SOURCE or "UNK", SCRIPT_BRANCH or "UNK", VERSION or "UNK", standVersion, BRANCH_LAST_COMMIT or "DEV BUILD", lang.get_current(), content)
        )
        async_http.dispatch()
        logs:close()
    else
        util.toast("Could not read your stand log file")
    end
end)

SCRIPT_DEBUG = SCRIPT_SOURCE == nil

function try_require(name, isOptional)
    local status, data = pcall(require, name)
    if status then
        return data
    else
        if data then
            Log.warn(name .. ": " .. data, TOAST_ALL)
        end
        if SCRIPT_SOURCE == "REPO" then
            if isOptional then
                Log.debug("Missing optional dependency: " .. name)
            else
                util.toast("Missing a required depencency (\"" .. name .. "\"). Please install this from the repo > dependencies list")
                Log.severe("Missing required dependency:", name)
            end
        elseif download_lib_update then
            local lockPath = download_lib_update(name, function()
                Log.log("Downloaded ", isOptional and "optional" or "required", "library:", name)
            end)
            while filesystem.exists(lockPath) do
                util.yield(500)
            end
            return require(name)
        end
        return nil
    end
end
-- END TEMPLATE --


util.require_natives(1627063482)

-- Models[1] && Models[2] are engines
local TRAIN_MODELS = {
    util.joaat("metrotrain"), util.joaat("freight"), util.joaat("freightcar"), util.joaat("freightcar2"), util.joaat("freightcont1"), util.joaat("freightcont2"), util.joaat("freightgrain"), util.joaat("tankercar")
}
local last_train = 0
local last_metro_f = 0
local last_metro_b = 0
local last_train_menu = 0
local globalTrainSpeed = 15
local globalTrainSpeedControlEnabled = false

show_busyspinner("Loading Train Models")
for _, model in ipairs(TRAIN_MODELS) do
    STREAMING.REQUEST_MODEL(model)
    while not STREAMING.HAS_MODEL_LOADED(model) do
        util.yield()
    end
end
HUD.BUSYSPINNER_OFF()

local spawnedMenu = menu.list(menu.my_root(), "Spawned Train Management", {}, "")
local function spawn_train(variation, pos, direction) 
    local train = VEHICLE.CREATE_MISSION_TRAIN(variation, pos.x, pos.y, pos.z, direction or false)
    local carts = {}
    for i = 0, 100 do
        local cart = VEHICLE.GET_TRAIN_CARRIAGE(train, i)
        if cart == 0 then
            break
        end
        table.insert(carts, cart)
    end
    last_train = train
    
    local posTrain = ENTITY.GET_ENTITY_COORDS(last_train)
    local netid = NETWORK.NETWORK_GET_NETWORK_ID_FROM_ENTITY(train)
    NETWORK.NETWORK_REQUEST_CONTROL_OF_NETWORK_ID(netid)
    NETWORK.SET_NETWORK_ID_CAN_MIGRATE(netid, false)
    -- Setup menu actions (set speed, delete, etc)
    local submenu = menu.list(spawnedMenu, "Train " .. last_train, {"train" .. last_train}, "") 
    menu.slider(submenu, "Set Speed", {"setspeedtrain" .. last_train}, "Sets this spawned train's speed. Values over +/- 80 will result in players sliding backwards. Reversing trains will look desynced to other players.", -250, 250, 10, 5, function(value, prev)
        VEHICLE.SET_TRAIN_CRUISE_SPEED(train, value)
        VEHICLE.SET_TRAIN_SPEED(train, value)
    end)

    menu.toggle(submenu, "Derail", {"derailtrain" .. last_train}, "Visually derails the train", function(on)
        VEHICLE.SET_RENDER_TRAIN_AS_DERAILED(train, on)
    end, false)

    menu.action(submenu, "Delete Engine", {"deleteengine" .. last_train}, "Deletes the spawned train's engine", function(v)
        entities.delete(train)
    end)

    menu.action(submenu, "Delete", {"deletetrain" .. last_train}, "Deletes the spawned train", function(v)
        for _, cart in ipairs(carts) do
            entities.delete(cart)
        end
        menu.delete(submenu)
    end)

    util.toast(string.format("Train spawned at (%.1f, %.1f, %.1f) variant %d", posTrain.x, posTrain.y, posTrain.z, variation))
    last_train_menu = submenu
    return train
end

-- MENU SETUP


menu.divider(menu.my_root(), "Train Spawning")

menu.click_slider(menu.my_root(), "Spawn Train", {"spawntrain"}, "Spawns a train with a certain variation\n22 = Metro\n23 = Long Train", 1, 25, 1, 1, function(variation)
    local ped = PLAYER.GET_PLAYER_PED_SCRIPT_INDEX(players.user())
    local pos = ENTITY.GET_ENTITY_COORDS(ped, 1)

    spawn_train(variation - 1, pos)
end)

menu.action(menu.my_root(), "Spawn Metro Train", {"spawnmetro"}, "Spawn a metro train", function()
    local ped = PLAYER.GET_PLAYER_PED_SCRIPT_INDEX(players.user())
    local pos = ENTITY.GET_ENTITY_COORDS(ped, 1)
    local metroFront = VEHICLE.CREATE_MISSION_TRAIN(21, pos.x, pos.y, pos.z, false)
    local metroBack = VEHICLE.CREATE_MISSION_TRAIN(21, pos.x, pos.y, pos.z, true)
    VEHICLE.SET_TRAIN_CRUISE_SPEED(metroFront, 15)
    util.yield(155)
    VEHICLE.SET_TRAIN_CRUISE_SPEED(metroBack, -15)
    VEHICLE.SET_TRAIN_SPEED(metroBack, -15)
    last_metro_f = metroFront
    last_metro_b = metroBack
    last_train = last_metro_f
end)

menu.slider(menu.my_root(), "Set Spawned Train Speed", {"setspawnedspeed"}, "Sets last spawned train's speed. Values over +/- 80 will result in players sliding backwards. Reversing trains will look desynced to other players.", -250, 250, 10, 5, function(value)
    VEHICLE.SET_TRAIN_CRUISE_SPEED(last_train, value)
    VEHICLE.SET_TRAIN_SPEED(last_train, value)
    if last_train == last_metro_f then
        VEHICLE.SET_TRAIN_CRUISE_SPEED(last_metro_b, -value)
        VEHICLE.SET_TRAIN_SPEED(last_metro_b, -value)
    end
end)

menu.action(menu.my_root(), "Delete Last Spawned Train", {"delltrain"}, "Deletes the last spawned train", function(v)
    if last_train > 0 then
        if last_train == last_metro_f then
            if last_metro_f > 0 then
                entities.delete(last_metro_f)
                last_metro_f = 0
            end
            if last_metro_b > 0 then
                entities.delete(last_metro_b)
                last_metro_b = 0
            end
            return
        end
        if not ENTITY.DOES_ENTITY_EXIST(last_train) then
            menu.delete(last_train_menu)
            last_train = 0
            last_train_menu = 0
            return
        end
        local carts = {}
        for i = 0, 100 do
            local cart = VEHICLE.GET_TRAIN_CARRIAGE(last_train, i)
            if cart == 0 then
                break
            end
            table.insert(carts, cart)
        end
        entities.delete(last_train)
        for _, cart in ipairs(carts) do
            entities.delete(cart)
        end
        menu.delete(last_train_menu)
        last_train = 0
        last_train_menu = 0
    end
end)

menu.divider(menu.my_root(), "Global")

menu.toggle(menu.my_root(), "Global Speed Enabled", {"enableglobalspeed", "trainspeed"}, "Should script control all trains? (Speed set below)", function(on)
    -- Should _probably_ check if the model is a ya know train but ehh
    globalTrainSpeedControlEnabled = on
end, globalTrainSpeedControlEnabled)

menu.slider(menu.my_root(), "Global Train Speed", {"settrainspeed", "trainspeed"}, "Sets all nearby train's speed. Values over +/- 80 will result in players sliding backwards. Reversing trains will look desynced to other players.", -250, 250, globalTrainSpeed, 5, function(value)
    globalTrainSpeed = value
end)

menu.action(menu.my_root(), "Delete All Trains", {"delalltrains"}, "Deletes all trains in the game", function(v)
    local vehicles = entities.get_all_vehicles_as_handles()
    local count = 0
    for _, vehicle in pairs(vehicles) do
        local vehicleModel = ENTITY.GET_ENTITY_MODEL(vehicle)
        for _, model in ipairs(TRAIN_MODELS) do
            -- Check if the vehicle is a train
            if model == vehicleModel then
                count = count + 1
                entities.delete(vehicle)
                break
            end
        end
    end
    util.toast("Deleted " .. count .. " trains")
end)

menu.toggle(menu.my_root(), "Derail Trains", {"setderailed"}, "Makes all trains render as derailed", function(on)
    local vehicles = entities.get_all_vehicles_as_handles()
    for _, vehicle in pairs(vehicles) do 
        local vehicleModel = ENTITY.GET_ENTITY_MODEL(vehicle)
        for _, model in ipairs(TRAIN_MODELS) do
            -- Check if the vehicle is a train
            if model == vehicleModel then
                VEHICLE.SET_RENDER_TRAIN_AS_DERAILED(vehicle, on)
            end
        end
    end
end, false)

util.on_stop(function(_)
    for _, model in ipairs(TRAIN_MODELS) do
        STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(model)
    end
end)


local crazyTrains = false
menu.toggle(menu.my_root(), "Broken Trains", {}, "", function(on)
    crazyTrains = on
end, crazyTrains)


local textc = {
    r = 255,
    g = 255,
    b = 255,
    a = 0
}
local speed = 0.0
local tick = 0
local increment = 5.0
while true do
    if crazyTrains then
        directx.draw_text(0.2, 0.5, string.format("speed %3.0f %s", speed, (increment > 0.0 and " forward" or " backwards")), 1, 0.5, textc, false)
        tick = tick + 1
        if tick > 20 then
            speed = speed + increment
            if speed == 0.0 then
                speed = increment
            elseif speed >= 80.0 or speed <= -80.0 then
                increment = -increment
            end
            local vehicles = entities.get_all_vehicles_as_handles()
            for k, vehicle in pairs(vehicles) do
                VEHICLE.SET_TRAIN_CRUISE_SPEED(vehicle, speed)
                VEHICLE.SET_TRAIN_SPEED(vehicle, speed)
            end
            tick = 0
        end
    elseif globalTrainSpeedControlEnabled then
        for _, vehicle in pairs(entities.get_all_vehicles_as_handles()) do
            local model = ENTITY.GET_ENTITY_MODEL(vehicle)
            if model == TRAIN_MODELS[1] or model == TRAIN_MODELS[2] then --Only need to set speed for engine
                local netid = NETWORK.NETWORK_GET_NETWORK_ID_FROM_ENTITY(vehicle)
                NETWORK.SET_NETWORK_ID_CAN_MIGRATE(netid, true)
                NETWORK.NETWORK_REQUEST_CONTROL_OF_ENTITY(vehicle)
                NETWORK.NETWORK_REQUEST_CONTROL_OF_NETWORK_ID(netid)
                
                VEHICLE.SET_TRAIN_CRUISE_SPEED(vehicle, globalTrainSpeed)
                VEHICLE.SET_TRAIN_SPEED(vehicle, globalTrainSpeed)
            end
        end
    end
    util.yield()
end
