return {
	["height"] = 0.175,
	["text_y_offset"] = -0.0055555555,
	["padding"] = 0.003125,
	["maxOptions"] = 7,
	["border"] = 0.0,
	["header"] = [[juuzo_banner.png]],
	["x"] = 0.254,
	["y"] = 0.506,
	["feature_offset"] = 0.025,
	["width"] = 0.2,
	["textSize"] = 1.1,
	["colorText"] = {
		["r"] = 255,
		["g"] = 255,
		["b"] = 255,
		["a"] = 200,
	},
	["side_window"] = {
		["on"] = true,
		["spacing"] = 0.0547222,
		["padding"] = 0.01,
		["width"] = 0.3,
		["offset"] = {
			["x"] = 0,
			["y"] = 0,
		},
	},
	["feature_scale"] = {
		["x"] = 0.2,
		["y"] = 0.025,
	},
	["footer"] = {
		["footer_pos_related_to_background"] = true,
		["draw_footer"] = true,
		["footer_y_offset"] = 0,
		["padding"] = 0.0078125,
		["footer_size"] = 0.019444444,
	},
	["mainColour"] = {
		["r"] = 210,
		["g"] = 0,
		["b"] = 255,
		["a"] = 255,
	},
	["menuSaveToggles"] = {
		["ALTER_WANTED_LEVEL_EVENT"] = false,
		["typingState"] = true,
		["REQUEST_PICKUP_EVENT"] = false,
		["vip"] = false,
		["controllerSupport"] = false,
		["embedScripts"] = false,
		["KICK_VOTES_EVENT"] = false,
		["typing"] = true,
		["paused"] = false,
	},
	["featColour"] = {
		["r"] = 0,
		["g"] = 0,
		["b"] = 0,
		["a"] = 0,
	},
	["backColour"] = {
		["r"] = 255,
		["g"] = 0,
		["b"] = 255,
		["a"] = 40,
	},
}