return {
	["gradRightColour"] = {
		["a"] = 255,
		["b"] = 118,
		["g"] = 28,
		["r"] = 27,
	},
	["featColour"] = {
		["a"] = 0,
		["b"] = 0,
		["g"] = 0,
		["r"] = 0,
	},
	["maxOptions"] = 7,
	["menuSaveToggles"] = {
		["typingState"] = true,
		["paused"] = false,
		["ALTER_WANTED_LEVEL_EVENT"] = false,
		["typing"] = true,
		["controllerSupport"] = false,
		["vip"] = false,
		["embedScripts"] = false,
		["REQUEST_PICKUP_EVENT"] = false,
		["KICK_VOTES_EVENT"] = false,
	},
	["feature_offset"] = 0.027083333333333,
	["text_y_offset"] = -0.0055555555,
	["header"] = [=[juuzo_banner.png]=],
	["footer"] = {
		["footer_size"] = 0.019444444,
		["draw_footer"] = true,
		["footer_pos_related_to_background"] = true,
		["footer_y_offset"] = 0,
		["padding"] = 0.0078125,
	},
	["menuKeys"] = {
		["up"] = 38,
		["sideScrollRight"] = 39,
		["setHotkey"] = 122,
		["back"] = 8,
		["select"] = 13,
		["down"] = 40,
		["open"] = 116,
		["sideScrollLeft"] = 37,
	},
	["side_window"] = {
		["offset"] = {
			["y"] = 0,
			["x"] = 0.0,
		},
		["on"] = true,
		["width"] = 0.3,
		["spacing"] = 0.0547222,
		["padding"] = 0.01,
	},
	["backColour"] = {
		["a"] = 60,
		["b"] = 255,
		["g"] = 0,
		["r"] = 0,
	},
	["width"] = 0.2,
	["fontID"] = 9,
	["border"] = 0.0018518518518519,
	["mainColour"] = {
		["a"] = 255,
		["b"] = 255,
		["g"] = 0,
		["r"] = 0,
	},
	["textSize"] = 1.1,
	["feature_scale"] = {
		["y"] = 0.025,
		["x"] = 0.2,
	},
	["colorText"] = {
		["a"] = 200,
		["b"] = 255,
		["g"] = 255,
		["r"] = 255,
	},
	["font"] = [=[Neufreit.spritefont]=],
	["states"] = {
		["teleport"] = false,
		["paused"] = false,
		["Dead Eye"] = false,
		["Grapple Gun"] = false,
		["RGB Neons"] = false,
		["embedScripts"] = true,
		["KICK_VOTES_EVENT"] = false,
		["Night Vision"] = false,
		["tiny"] = false,
		["Cartoon Gun"] = false,
		["Rapid Fire"] = false,
		["ALTER_WANTED_LEVEL_EVENT"] = false,
		["uwu"] = false,
		["Paint Gun"] = false,
		["No Grip"] = false,
		["REQUEST_PICKUP_EVENT"] = false,
		["Draw Crosshair"] = false,
		["No Idle Cam"] = true,
		["idle"] = false,
		["cartoon"] = false,
		["ped"] = false,
		["typing"] = true,
		["GTA4 Neons"] = false,
		["Silent Aimbot Ped"] = false,
		["Silent Aimbot Player"] = false,
		["Dust Gun"] = false,
		["Money Gun"] = false,
		["pedAimbot"] = false,
		["rapidFire"] = false,
		["dust"] = false,
		["Tiny Player"] = false,
		["Spike Cam"] = false,
		["delete"] = false,
		["paint"] = false,
		["money"] = false,
		["heat"] = false,
		["Respawn at death coords"] = false,
		["2k Money Drop"] = false,
		["Object Gun"] = false,
		["reduced"] = false,
		["No Target"] = false,
		["crosshair"] = false,
		["Dildo Gun"] = false,
		["Reduced Vehicle Collision"] = false,
		["Exhaust Trails"] = false,
		["controllerSupport"] = false,
		["playerAimbot"] = false,
		["object"] = false,
		["Heat Vision"] = false,
		["Ped Gun"] = false,
		["cop"] = false,
		["CLEAR_TASK"] = false,
		["moneyGun"] = false,
		["Teleport Gun"] = false,
		["night"] = false,
		["Recon Drone"] = false,
		["dildo"] = false,
		["BlackParade"] = false,
		["grapple"] = false,
		["Delete Gun"] = false,
		["Reduced Collision"] = false,
		["REPORT_MYSELF"] = false,
		["FlashMod"] = false,
		["instantly Enter & Exit Vehicle"] = false,
		["Become A Cop"] = false,
		["vip"] = false,
	},
	["padding"] = 0.003125,
	["y"] = 0.372,
	["x"] = 0.256,
	["saveable_ints"] = {
		[1] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 16437,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 45,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[2] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[3] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[4] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[5] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[6] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[7] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[8] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[9] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["thread"] = 0,
			["real_value"] = 1,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_max"] = 130,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_type"] = 1034,
			["name"] = [=[Field Of View]=],
		},
		[10] = {
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["real_type"] = 1034,
			["thread"] = 0,
			["real_hidden"] = false,
			["real_mod"] = 2,
			["index"] = 2,
			["real_value"] = 1,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_max"] = 130,
			["name"] = [=[Field Of View]=],
		},
		[11] = {
			["real_value"] = 1,
			["parent"] = {
				["id"] = 1,
			},
			["real_id"] = 779,
			["thread"] = 0,
			["real_mod"] = 2,
			["real_hidden"] = false,
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["index"] = 2,
			["real_max"] = 130,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_type"] = 1034,
			["name"] = [=[Field Of View]=],
		},
		[12] = {
			["real_id"] = 779,
			["real_max"] = 130,
			["real_hidden"] = false,
			["parent_id"] = 1,
			["real_min"] = 1,
			["real_mod"] = 2,
			["real_type"] = 1034,
			["hierarchy_key"] = [=[Player.Field_Of_View]=],
			["index"] = 2,
			["real_value"] = 1,
			["parent"] = {
				["id"] = 1,
			},
			["thread"] = 0,
			["name"] = [=[Field Of View]=],
		},
		["Field Of View"] = 1,
	},
	["height"] = 0.18958333333333,
}